# Generated by Django 4.2 on 2023-06-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ramazonapp', '0002_product_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
